name: project_taxcar


publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.2+9

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter_swiper_plus: 2.0.4
  flutter:
    sdk: flutter

 
  
  fluttertoast: ^8.0.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: Fontlogin
      fonts:
        - asset: assets/font/Taviraj-Bold.ttf
    - family: Font
      fonts:
        - asset: assets/font/Prompt-Light.ttf
        - asset: assets/font/Prompt-Bold.ttf
        - asset: assets/font/Prompt-Medium.ttf